[window]
startup_mode = "Maximized"

[font]
# size = 10
# normal = { family = "Gohu GohuFont" }

size = 12
normal = { family = "ProggyCleanTT" }

# size = 8
# normal = { family = "IBM VGA 8x16" }
bold = { style = "Regular" }

[mouse]
hide_when_typing = true

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
